### ISSUE TITLE
XML parsing error (bug)

### ISSUE THREAD

**Issue by RazuvaevDD** [RazuvaevDD/ProjectWork2019Neiro#22]
@AverinLV When trying to get settings from a non-existent or empty XML file, exception handling does not occur.

_Originally posted by @RazuvaevDD in https://github.com/RazuvaevDD/ProjectWork2019Neiro/pull/21#issuecomment-475984713_

**Comment by AverinLV** [comment]
It's impossible to get settings from non-existent file because constructor of XMLParser create new file if name of file in argument does not exist. It's only possible with empty file and it's fixed in fbc2dc6

**Comment by RazuvaevDD** [comment]
Ok
